version: '3.9'
services:

  person-service:
    image: ssamoilenko/hsal5-stress-test:latest
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.native
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/persons
      - APP_ENTITY_COUNT=100000
      - APP_PREPOPULATE_PERCENTAGE=75
    ports:
      - '8080:8080'
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: bitnami/mongodb
    container_name: mongodb
    restart: always
    volumes:
      - ./data/mongodb:/bitnami/mongodb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '27017:27017'
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping').ok", "--quiet" ]
      interval: 5s
      timeout: 5s
      retries: 10
