### GET random person
GET localhost:8080/person/random

### GET person
GET localhost:8080/person?firstName=John&lastName=Doe

### POST random person
POST localhost:8080/person/random

### POST person
POST localhost:8080/person
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "age": 44,
    "phoneNumber": "2053542636"
}

### GET person count
GET localhost:8080/person/count

### DELETE all persons
DELETE localhost:8080/person/all
